services:
  db:
    container_name: db-gym-app-dev
    image: postgres:16
    restart: always
    volumes:
      - db_data_dev:/var/lib/postgresql/data
  redis:
    container_name: redis-gym-app-dev
    image: redis:7.2
    restart: always
    volumes:
      - redis_data_dev:/data
  mongo:
    container_name: mongo-gym-app-dev
    image: mongo:8
    restart: always
    volumes:
      - mongo_data_dev:/data/db
volumes:
  db_data_dev:
  redis_data_dev:
  mongo_data_dev: