#SPRING CONFIG
spring.application.name=gym-app
spring.config.import=optional:file:.env[.properties]
spring.main.banner-mode=off
spring.threads.virtual.enabled=true
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

#JPA - HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# Batch processing, for async operations
spring.jpa.properties.hibernate.jdbc.batch_size=25
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Form f(x) = (CPU cores * 2) + disk's.
spring.datasource.hikari.maximum-pool-size=20

# Avoid allow the connection be alive always
spring.datasource.hikari.max-lifetime=180000

# Avoid asks the sequence id value.
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# Maximum time to await after Thread's fail.
spring.datasource.hikari.connection-timeout=30000

# Avoid that unactive connections dies by surprising.
spring.datasource.hikari.idle-timeout=600000

#DATASOURCE CONFIG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

#JWT CONFIG
jwt.secret.key=${JWT_SECRET}
jwt.secret.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

#REDIS
redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}
redis.password=${REDIS_PWD}
redis.url=${REDIS_URL}
redis.password.dev=${REDIS_PWD_DEV}

#SPRING REDIS
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PWD_DEV}
#spring.data.redis.url=${REDIS_URL}
spring.data.redis.ssl.enabled=false
spring.data.redis.database=0
#spring.data.redis.client-type=jedis

#APP
app.uri=${APP_URI}
app.user.admin.email=${ADMIN_EMAIL}
app.user.admin.password=${ADMIN_PWD}
app.user.email=${USER_EMAIL}
app.user.password=${USER_PWD}

app.mapping.auth=${MAP_AUTH}
app.mapping.admin=${APP_ADMIN_MAPPING}
app.mapping.user=${APP_USER_MAPPING}

#SPRING SECURITY
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_URL_DEV}

spring.mail.host=${APP_MAIL_HOST}
spring.mail.port=${APP_MAIL_PORT}
spring.mail.username=${APP_MAIL_USER}
spring.mail.password=${APP_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.debug=true
