spring.config.import=optional:configtree:/run/secrets/, optional:file:.env.prod[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.auth.redirect-url=${APP_AUTH_REDIRECT_URL}
app.auth.redirect.url.password-reset=${APP_AUTH_REDIRECT_URL_RESET}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${db_password}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.password=${redis_password}
spring.data.redis.ssl.enabled=true

spring.data.mongodb.host=hostIpOnWhichMongoIsRunning
spring.data.mongodb.auto-index-creation=true

jwt.secret.key=${JWT_SECRET}
jwt.secret.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

app.uri=${APP_URI}
app.mapping.auth=${MAP_AUTH}
app.mapping.admin=${APP_ADMIN_MAPPING}
app.mapping.user=${APP_USER_MAPPING}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.registration.facebook.client-id=${FACEBOOK_CLIENT_ID}
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_CLIENT_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile

# STRIPE PROD
stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.success-url=${STRIPE_SUCCESS_URL}
stripe.cancel-url=${STRIPE_CANCEL_URL}

app.payment.reconciliation.interval=300000

spring.mail.host=${APP_MAIL_HOST}
spring.mail.port=${APP_MAIL_PORT}
spring.mail.username=${APP_MAIL_USER}
spring.mail.password=${APP_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.debug=false

app.backup.db.command.host=${BACKUP_HOST}
app.backup.db.command.port=${BACKUP_PORT}
app.backup.db.command.username=${DATASOURCE_USERNAME}
app.backup.db.command.password=${db_password}
app.backup.db.command.database=${DB_NAME}
app.backup.db.command.directory=${BACKUP_DIRECTORY:/app/backups}

app.scheduler.config.thread-name-prefix=scheduler-app-thread
app.scheduler.config.pool-size=20
app.scheduler.config.await-termination-seconds=60