#SPRING CONFIG
spring.application.name=gym-app
spring.threads.virtual.enabled=true
spring.config.import=optional:file:.env[.properties]
spring.main.banner-mode=off

#JPA - HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

#DATASOURCE CONFIG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

#JWT CONFIG
jwt.secret.key=${JWT_SECRET}
jwt.secret.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

#REDIS
redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}
redis.password=${REDIS_PWD}
redis.url=${REDIS_URL}
redis.password.dev=${REDIS_PWD_DEV}

#SPRING REDIS
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PWD_DEV}
spring.redis.url=${REDIS_URL}
spring.redis.ssl.enabled=false
spring.redis.database=0
spring.redis.client-type=jedis

#APP
app.uri=${APP_URI}
app.user.admin.email=${ADMIN_EMAIL}
app.user.admin.password=${ADMIN_PWD}
app.user.email=${USER_EMAIL}
app.user.password=${USER_PWD}

app.mapping.auth=${MAP_AUTH}
app.mapping.admin=${APP_ADMIN_MAPPING}
app.mapping.user=${APP_USER_MAPPING}

#SPRING SECURITY
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_URL_DEV}

spring.mail.host=${APP_MAIL_HOST}
spring.mail.port=${APP_MAIL_PORT}
spring.mail.username=${APP_MAIL_USER}
spring.mail.password=${APP_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.debug=true
