#SPRING CONFIG
spring.application.name=gym-app
spring.threads.virtual.enable=true
spring.config.import=optional:file:.env[.properties]
spring.main.banner-mode=off

#JPA - HIBERNATE
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

#DATASOURCE CONFIG
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

#JWT CONFIG
jwt.secret.key=${JWT_SECRET}
jwt.secret.expiration=${JWT_ACCESS_EXPIRATION}
jwt.refresh.key=${JWT_SECRET}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}

#REDIS
redis.host=${REDIS_HOST}
redis.port=${REDIS_PORT}
redis.password=${REDIS_PASSWORD}
redis.url=${REDIS_URL}

#APP
app.uri=${APP_URI}
app.user.admin.email=${ADMIN_EMAIL}
app.user.password=${ADMIN_PWD}

app.mapping.auth=${MAP_AUTH}

#SPRING SECURITY
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${REDIRECT_URL_DEV}
