package com.jame.dev.gymApp.application.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCodes {

   NOT_FOUND("NOT_FOUND_OPERATION"),
   ACCESS("ACCESS_OPERATION"),
   ACCESS_DENIED("ACCESS_DENIED"),
   NO_ACCESS("NO_ACCESS"),
   LOGOUT("LOGOUT_OPERATION"),
   EXTRACTION("EXTRACTION_OPERATION"),
   AUTHENTICATION("AUTHENTICATION_OPERATION"),
   AUTHORIZATION("AUTHORIZATION_OPERATION"),
   VALIDATION("VALIDATION_OPERATION"),
   ARGUMENT("ARGUMENT_OPERATION"),
   CONSTRAINT("CONSTRAINT_OPERATION"),
   UNSUPPORTED("UNSUPPORTED_OPERATION"),
   INTERNAL("INTERNAL_OPERATION"),
   SAVE("SAVE_OPERATION"),
   UPDATE("UPDATE_OPERATION"),
   TYPE("TYPE_MISMATCH"),
   VERIFICATION("VERIFICATION_OPERATION");

   private final String code;

   @Override
   public String toString() {
      return this.code;
   }
}
